name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
          